SEND_BROKEN_LINK_EMAILS = True

EMAIL_HOST = "smtp.google.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "HAL@decode72.com"
EMAIL_HOST_PASSWORD = "geauxmice"
DEFAULT_FROM_EMAIL = "HAL@decode72.com"
SERVER_EMAIL = "HAL@decode72.com"
